import { parseAbi, type Address } from "viem";

export const BURNTATO_DEPLOYMENT = {
  chainId: 11_155_111,
  diamond: "0xdaD8812ac9F829c09808cBaB98b316042D9C7142" as Address,
  deploymentBlock: 11_518_114n,
  sourceCommit: "5d5dd21",
} as const;

export const burntatoAbi = parseAbi([
  "struct ProtocolConfig { uint256 startingPrice; uint16 priceIncreaseBps; uint256 roundTimeout; uint256 roundEmissionBudget; uint16 emissionStepBps; uint256 emissionVestingDuration; uint16 winnerBps; uint16 recoveryBps; uint16 treasuryBps; uint16 recoveryBurnBps; uint16 recoveryTreasuryBps; uint16 buybackBps; uint256 roundTimeoutDecay; uint256 minimumRoundTimeout; }",
  "struct RoundConfig { uint256 startingPrice; uint16 priceIncreaseBps; uint256 roundTimeout; uint256 roundEmissionBudget; uint16 emissionStepBps; uint256 emissionVestingDuration; uint16 winnerBps; uint16 recoveryBps; uint16 treasuryBps; uint16 recoveryBurnBps; uint16 recoveryTreasuryBps; uint16 buybackBps; uint256 roundTimeoutDecay; uint256 minimumRoundTimeout; }",
  "struct Round { uint256 roundId; RoundConfig config; address currentHolder; uint256 holderSince; uint256 deadline; uint64 purchaseIndex; uint256 nextPrice; uint256 holderMaxReward; uint256 holderEarned; uint256 remainingEmission; uint256 emittedPotato; uint256 treasuryEmissionBudget; uint256 holderTreasuryMaxReward; uint256 holderTreasuryEarned; uint256 remainingTreasuryEmission; uint256 treasuryEmittedPotato; uint256 treasuryReleasedPotato; uint256 winnerPool; uint256 recoveryPool; uint256 recoveryCarryIn; uint256 totalCommitted; bool holderEmissionFinalized; bool activated; bool settled; }",
  "function currentRoundId() view returns (uint256)",
  "function protocolConfig() view returns (ProtocolConfig)",
  "function getRound(uint256 roundId) view returns (Round)",
  "function currentEarnedEmission() view returns (uint256 baseEarned, uint256 treasuryEarned)",
  "function purchasesPaused() view returns (bool)",
  "function commitmentsPaused() view returns (bool)",
  "function balanceOf(address account) view returns (uint256)",
  "function buyPotato() payable",
  "function materializeMaturedEmission() returns (uint256 baseEarned, uint256 treasuryEarned)",
  "function settleRound()",
  "function commitRecovery(uint256 amount)",
  "function recoveryCommitment(uint256 roundId, address account) view returns (uint256)",
  "function totalRecoveryCommitment(uint256 roundId) view returns (uint256)",
  "function claimWinner(uint256 roundId, address recipient) returns (uint256)",
  "function claimRecovery(uint256 roundId, address recipient) returns (uint256)",
  "function winnerClaimed(uint256 roundId) view returns (bool)",
  "function recoveryClaimed(uint256 roundId, address account) view returns (bool)",
  "function claimableRecovery(uint256 roundId, address account) view returns (uint256)",
  "event RoundStarted(uint256 indexed roundId, uint256 startingPrice, uint256 remainingEmission)",
  "event PotatoPurchased(uint256 indexed roundId, address indexed buyer, uint256 price, uint256 purchaseIndex, uint256 maxReward, uint256 deadline)",
  "event EmissionFinalized(uint256 indexed roundId, address indexed holder, uint256 maxReward, uint256 earned, uint256 heldSeconds)",
  "event TreasuryRewardFinalized(uint256 indexed roundId, address indexed holder, uint256 maxReward, uint256 earned, uint256 heldSeconds)",
  "event RecoveryCommitted(uint256 indexed roundId, address indexed account, uint256 amount, uint256 totalCommitted)",
  "event RoundSettled(uint256 indexed roundId, address indexed winner, uint256 winnerPool, uint256 recoveryPool, uint256 totalCommitted, uint256 burnedPotato, uint256 treasuryPotato)",
  "event WinnerClaimed(uint256 indexed roundId, address indexed winner, address indexed recipient, uint256 amount)",
  "event RecoveryClaimed(uint256 indexed roundId, address indexed account, address indexed recipient, uint256 amount)",
  "error AlreadyClaimed()",
  "error AlreadyFinalized()",
  "error CommitmentClosed(uint256 roundId)",
  "error CommitmentsPaused()",
  "error IncorrectPayment(uint256 expected, uint256 actual)",
  "error InsufficientBalance()",
  "error InvalidAddress()",
  "error InvalidRound(uint256 roundId)",
  "error NativeTransferFailed()",
  "error NoCurrentHolder()",
  "error NothingToClaim()",
  "error PurchasesPaused()",
  "error Reentrancy()",
  "error RoundAlreadySettled()",
  "error RoundExpired()",
  "error RoundNotExpired()",
  "error UnauthorizedWinner(address account)",
  "error VestingIncomplete()",
  "error ZeroAmount()",
]);
